const productList = [
    {
        id: 0,
        productImg: require('../assets/img/biryani.jpg'),
        productTitle: "Biryani",
        productPrice: 5,
        productDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        productType: 'future',
    },
    {
        id: 1,
        productImg: require('../assets/img/burger.jpg'),
        productTitle: "Burger",
        productPrice: 12,
        productDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        productType: 'future',
    },
    {
        id: 2,
        productImg: require('../assets/img/chinese.jpg'),
        productTitle: "Chinese",
        productPrice: 8,
        productDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        productType: 'future',
    },
    {
        id: 3,
        productImg: require('../assets/img/coffee.jpg'),
        productTitle: "Coffee",
        productPrice: 4,
        productDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        productType: 'normal',
    },
    {
        id: 4,
        productImg: require('../assets/img/drink.jpg'),
        productTitle: "Drink",
        productPrice: 3,
        productDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        productType: 'future',
    },
    {
        id: 5,
        productImg: require('../assets/img/friedChicken.jpg'),
        productTitle: "Fried Chicken",
        productPrice: 16,
        productDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        productType: 'normal',
    },
    {
        id: 6,
        productImg: require('../assets/img/juice.jpg'),
        productTitle: "Juice",
        productPrice: 7,
        productDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        productType: 'normal',
    },
    {
        id: 7,
        productImg: require('../assets/img/pasta.jpg'),
        productTitle: "Pasta",
        productPrice: 11,
        productDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        productType: 'future',
    },
    {
        id: 8,
        productImg: require('../assets/img/pizza.jpg'),
        productTitle: "Pizza",
        productPrice: 25,
        productDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        productType: 'normal',
    },
    {
        id: 9,
        productImg: require('../assets/img/soup.jpg'),
        productTitle: "Soup",
        productPrice: 13,
        productDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        productType: 'normal',
    },
    {
        id: 10,
        productImg: require('../assets/img/sweetdish.jpg'),
        productTitle: "Sweet Dish",
        productPrice: 30,
        productDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        productType: 'normal',
    },
    {
        id: 11,
        productImg: require('../assets/img/tea.jpg'),
        productTitle: "Tea",
        productPrice: 9,
        productDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        productType: 'future',
    }
];


export default productList;